### ISSUE TITLE
Load XML file does notwork

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#101]
I can select the file but when I select Load XML File nothing happens

**Comment by spacejang** [comment]
Hello Peter,

You should create brand new file and load it since I added/ deleted some attributes.
Or
Send me your xml file. I will try it.
Thanks

**Comment by peterbomberg** [comment]
Tried creating new files still get the same result

**Comment by spacejang** [comment]
Hello Peter,
Could you please send me your saved new xml file by email.
I would like to test it...

**Comment by peterbomberg** [comment]
worked just now
