### ISSUE TITLE
non-medical ingredients separation

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#13]
Part III - ABOUT THIS MEDICATION 

Add ‘+’ and ‘-‘ buttons and make granular; i.e., one line per non-medicinal ingredient. 
non-medicinal ingredient #1
non-medicinal ingredient #2         

Priority - H

**Comment by maadarani** [comment]
What does make Granular mean?

**Comment by maadarani** [comment]
In About this Medication, there are these fields:
WHAT THE MEDICATION IS USED FOR
WHAT IT DOES
WHEN IT SHOULD NOT BE USED
WHAT THE MEDICINAL INGREDIENT IS
WHAT THE NONMEDICINAL INGREDIENTS ARE
WHAT DOSAGE FORMS IT COMES IN

Do we ONLY want ADD and REMOVE functionality (assuming this was meant by granular) on "WHAT THE NONMEDICINAL INGREDIENTS ARE"?

**Comment by MartinBernard** [comment]
Disregard this one for now.
