### ISSUE TITLE
validation messages

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#14]
All - Validation

Insert Validation Messages

Priority - M

**Comment by ericgrandmaison** [comment]
Phase 1 - validation only on the form
Phase 2 - validation of the xml file itself
Dates format: yyyy-mm-dd

**Comment by maadarani** [comment]
Confirm if these are the "validation message" items. Also see comments.
1/ Drop menus need help text (eg “Select xyz”) to be added to the list and shown as default selection 
- will add

2/ In date fields, when no date is yet selected, display the following 'mm dd, yyyy' 
- textbox is ready only. it's a date picker. when a date is picked, it auto populate the textbox
- date format is:
<cc1:CalendarExtender ID="CalendarExtender1" runat="server" TargetControlID="tbDateRev" Format="MMM d, yyyy" />
 
3/ Text fields need help text within the box (eg “What the medication is used for”).  When text is entered, the help text disappears. 
- see screenshot. Right above of most textboxes, there are labels that say what they are for

4/ When navigating away from form page, display popup message: Sure you want to leave? Are you sure you want to leave this page?
- navigating from page to page does not loss data. before it leaves the page, everything is saved in memory. why do you have to confirm?

5/ When uploading files, display a running tally and max file size
- running tally? number of images uploaded? max size?

6/ When entering text into a large text field, display the number of remaining characters
- what's the maximum?

**Comment by maadarani** [comment]
in addition to above
#2 
- format is already controlled in the calendar textbox
#3  
![label](https://cloud.githubusercontent.com/assets/6798647/10712355/ac8026ee-7a66-11e5-8d8a-0e8789684858.png)

**Comment by maadarani** [comment]
in addition to above
#2 
•format is already controlled in the calendar textbox

**Comment by maadarani** [comment]
in addition to above
#3 
![label](https://cloud.githubusercontent.com/assets/6798647/10712362/ea480bea-7a66-11e5-8036-7cd172c56d69.png)

**Comment by MartinBernard** [comment]
...not done yet.

**Comment by MartinBernard** [comment]
Some date fields have been changed to reflect yyyy-mm-dd however not all fields have been rectified. For example, last section of Part III is still incorrect.
