### ISSUE TITLE
expand/collapse sections

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#15]
All - Functionality

Add Expand/Collapse All Sections Function         

Priority - L

**Comment by maadarani** [comment]
As an example, do we want this much expand/collapse?
Currently, Dosage and Administration is one big expand/collapse.
Do we want Dosing Considerations has its own expand/collapse?
Do we want Recommended Dose and Dosage Adjustment has its own expand/collapse?
Do we want Missed Dose has its own expand/collapse?
Do we want Administration has its own expand/collapse?
Do we want Reconstitution has its own expand/collapse?
And under Reconstitution, Oral Solutions and Parenteral Products have their own expand/collapse too?
![sectioned](https://cloud.githubusercontent.com/assets/6798647/10712379/633035dc-7a67-11e5-8938-aeea1403a3d7.png)

**Comment by MartinBernard** [comment]
Leave for now. This comment will come back up during user testing.

**Comment by MartinBernard** [comment]
Ref #62 . close
