### ISSUE TITLE
Proper Use - header

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#19]
Part I - Proper Use of Medication - 

This section should be at the same level as Drug Interaction, Dosage and Administration, etc. It is now under subsection Overdosage.
This comment was provided previously however it must have been deleted by accident.        

Priority - H

**Comment by maadarani** [comment]
Do you mean ACTION AND CLINICAL PHARMACOLOGY?

**Comment by maadarani** [comment]
Are we referring to Part III,  PROPER USE OF THIS MEDICATIONÉ

**Comment by MartinBernard** [comment]
Yes. The whole section ACTION AND CLINICAL PHARMACOLOGY should be at the highest level where we can drill down to its content. FOr example, 

SUMMARY PRODUCT INFORMATION
INDICATIONS AND CLINICAL USE
CONTRAINDICATIONS
WARNINGS AND PRECAUTIONS

**Comment by MartinBernard** [comment]
I noticed you played around with this, I don't think you're done yet b/c it is not represented as requested.

**Comment by MartinBernard** [comment]
Checked again tonight and field "ACTION AND CLINICAL PHARMACOLOGY" is at the top of the form and missing many elements still embedded under overdosage. I'll wait to review in person before making more comments.

**Comment by maadarani** [comment]
OK. We need like a mockup to make sure I understand what you need.

**Comment by MartinBernard** [comment]
You had it also perfect before. All you needed is to bring up Action and Clinical Pharmacology up a level so it was in the expand collapse section immediately after overdosage. I'll provide a screen shot.

**Comment by MartinBernard** [comment]
Here's the screen shot. We can discuss more tomorrow.

![image](https://cloud.githubusercontent.com/assets/9659886/10987157/a623d038-83fe-11e5-997e-f9bf414f96ac.png)

Mechanism of Action box and Pharmackinetic goes under Header "Action and Clinical Pharmacology" which shuold be inserted between header "Overdosage" and "Storage and Stability"
