### ISSUE TITLE
scheduling symbol

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#2]
Cover - Scheduling symbol

Add controlled list of schedules linked to controlled library Scheduling images. E.g., drop down list of schedules. When user selects a schedule an image from Health Canada’s library will be used. Change the Schedule and the image changes to match.        

Priority - H

**Comment by ericgrandmaison** [comment]
Martin to provide list of schedules

**Comment by maadarani** [comment]
Confirming the change.
1/ add 'dropdown list of schedules' just above the image section (see screenshot)
2/ list of schedules (you already asked, this is fine)
3/ list of schedules will be added to the Controlled List xml file (same xml as the rest of dropdown lists, this is fine)
4/ add 'scheduling symbol image folder' as library of images
5/ user experience
- user pick a schedule in the dropdown list
- user click upload button
- code will get value from dropdown, search against the library, load the image 
![schedule](https://cloud.githubusercontent.com/assets/6798647/10712224/3fe2d1fc-7a62-11e5-816c-2eb4225f581d.png)
