### ISSUE TITLE
Mock-Ups (5 figures)

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#25]
We will need to review tomorrow. There are still many issues / concerns with the mock-ups.

I will be easier to complete in person. We're almost there. Keeping in mind this will probably change again after user testing.

[Visio-SPL_v3.pdf](https://github.com/hres/pmp/files/21694/Visio-SPL_v3.pdf)

**Comment by MartinBernard** [comment]
...the ability to add columns and rows within table is not there

**Comment by MartinBernard** [comment]
Make necessary changes as discussed today (ie: dropdown select, view display error, addition of column to table, etc,).

**Comment by maadarani** [comment]
We need to discuss adding columns; this is more complicated than rows and will require re-designing the table section. The fact that adding columns came after adding rows, I will have to change everything to make it happen and usable. We should chat about it.

**Comment by MartinBernard** [comment]
Let's keep this discussion for our meeting on Friday with Vik.

**Comment by MartinBernard** [comment]
Ref #62
