### ISSUE TITLE
Strength Field

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#27]
Priority - Medium

Strength field will have to be separated into 4 fields to allow capturing ingredients strengths like 20 mg /  3.4 ml.  

Strength (Value | Unit) and Strength per dosage (Value | Unit).

Please let me know if you need further clarification

For reference: [Structured PM and EL Comments.docx](https://github.com/hres/pmp/files/25449/Structured.PM.and.EL.Comments.docx)

**Comment by maadarani** [comment]
Can you elaborate more or give a mockup?

**Comment by MartinBernard** [comment]
For the cover letter page , it should look like this.

![image](https://cloud.githubusercontent.com/assets/9659886/10987535/36863f28-8402-11e5-8a15-5db5ef578e24.png)
