### ISSUE TITLE
General Comments (after population)

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#28]
- Tried to save draft after I completed Part 1 and lost all of my work
- Tried to hit the return button while in the table for Adverse reactions and I lost all of my work
- Some special characters wouldn't copy in but other would, subscript and superscript wouldn't copy in. 
- Took approx. 2 hours to complete all sections.

**Comment by maadarani** [comment]
I can't replicate it. Everything is saved in memory, even if you go from one page to another. will keep testing.

in regards of 2 hours to complete all sections comment, we have so many fields in there, and the form is very long, so I am not surprised that it took you that long.

**Comment by MartinBernard** [comment]
We will also continue to test to see if I can replicate the "lost work"

**Comment by MartinBernard** [comment]
After I entered information into the Molecular Mass section in Part 2 and tried to save a draft it crash.

However, today there was no lost work

**Comment by maadarani** [comment]
Probably it was when I was updating the code.
