### ISSUE TITLE
dosage form / strength

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#3]
Cover - Product title - 

Extremely important to separate Dosage Form, Strength and Unit of Measure into separate fields as is done in XEVMPD and IDMP:
1. Dosage Form (controlled list)
2. Strength (Free but with restricted to numerical values)
3. Unit of Measure (Controlled list)         

Priority - H

**Comment by ericgrandmaison** [comment]
Mike to create xml file with all controlled pick lists.  Sits on top of the other files, not hard coded into the page itself.

Eric will make changes to the xml file in the future, if items need to be added/removed.

**Comment by maadarani** [comment]
Currently, there's brand name, proper name, and dosage form/strength columns, total three columns.
Can you confirm, this task will give us these much columns (5), and these field functionalities?
Brand name (still a normal textbox)
Proper name (still a normal textbox)
Dosage Form (dropdown list, values from controlled list)
Strength (normal textbox, only numeric)
Unit of Measure (dropdown list, values from controlled list)

**Comment by MartinBernard** [comment]
@maadarani  - we will need to adjust the spacing for
Brand name | Proper name | Dosage Form | Strength | Unit of Measure

Brand Name, Proper Name, DF should all be wider while strength and unit of measure can be relatively small given the values that will go in.

**Comment by maadarani** [comment]
@MartinBernard Yup. Working on it, but had to stop for Vik's demo.

**Comment by MartinBernard** [comment]
no prob.

**Comment by MartinBernard** [comment]
@maadarani - Please add schedule and I will provide the library for the corresponding images.  Also load DF on Cover Page

**Comment by MartinBernard** [comment]
Unfortunately there is no library so you won't be able to use the Schedule drop down list for this field.  Can you use the following as the list of images. See section C01.004 (b) (i-iv) 
http://laws-lois.justice.gc.ca/eng/regulations/c.r.c.,_c._870/page-196.html#docCont

...................on the upper left quarter of the principal display panel

```
(i) the symbol “Pr” in the case of a prescription drug, but the symbol “Pr” shall not appear on the label of any other drug,

(ii) the symbol “Symbol consisting of a diamond shape outline in which an uppercase letter C is centred.” in a clear manner and a conspicuous colour and size, in the case of a controlled drug, other than a controlled drug contained in an agricultural implant and set out in Part III of the schedule to Part G,

(iii) the symbol “N” in a colour contrasting with the rest of the label or in type not less than half the size of any letters used thereon, in the case of a narcotic as defined in the Narcotic Control Regulations, and

(iv) in the case of a targeted substance as defined in subsection 1(1) of the Benzodiazepines and Other Targeted Substances Regulations, the following symbol in a colour contrasting with the rest of the label and in type not less than half the size of any other letter used on the main panel, namely,
Symbol consisting of a square outline divided in half from top left corner to bottom right corner. The top right half has an uppercase letter C inside and lower left half has an uppercase letter T inside.
```

**Comment by maadarani** [comment]
@MartinBernard I can only see 2 symbols in that list and 2 abbreviations. Is that what we need? I don't think this will work.

**Comment by MartinBernard** [comment]
Yes, we can turn Pr and N into images in order to make it work.

Pr
N
![crc870_ef002](https://cloud.githubusercontent.com/assets/9659886/10808625/f91bd2ea-7dc3-11e5-896b-74255070cd59.jpg)
![crc870_ef004](https://cloud.githubusercontent.com/assets/9659886/10808630/07c66c1a-7dc4-11e5-8601-2a3f4440fc7d.jpg)

**Comment by MartinBernard** [comment]
I noticed that the dosage form list does not load on the first cover page but it does in Part I - Summary Product Information

**Comment by maadarani** [comment]
That's probably you loaded it when I was working on it.

**Comment by MartinBernard** [comment]
can't see it how do I enable the view then? clear cache?

**Comment by maadarani** [comment]
Try again. IT could be cache issue related.
