### ISSUE TITLE
Part III - General Comments

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#31]
(1) Serious Side effects Table: There are often different titles in the last column. RIght now the table says "Stop Taking Drug" however we should be able to modify the wording for each column.

(2) Reporting Side Effects: missing this text at the end “Reporting Form and the adverse reaction reporting guidelines are available on the MedEffect™ Canada Web site at www.healthcanada.gc.ca/medeffect. 
NOTE: Should you require information related to the management of side effects, contact your health 
professional. The Canada Vigilance Program does not provide medical advice. |

**Comment by maadarani** [comment]
1) Confirm if you want me to change everything to text field that has the text inside it, but the user can change it.

**Comment by MartinBernard** [comment]
Yes but if you could pre-populate with the text already in there that would be helpful. It'll allow user to change it if they need which is not often but at least it'll be flexible.

**Comment by MartinBernard** [comment]
Another comment under Part III - Warnings and Precautions.....please remove statement "BEFORE you use   BRAND NAME   talk to your doctor or pharmacist if:"
