### ISSUE TITLE
Controlled Vocabulary ID

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#32]
Mike - can you confirm that for each controlled vocabulary terms, there is an equivalent unique ID. This will ensure proper management of those lists (ie: DF, RoA). You will be required to embed the actual ID as part of the XML file. We're recommending including it as an attribute.

Another question on this topic. As part of your validation messages when users load an existing XML, do you check to see if these line up with our current list?

**Comment by maadarani** [comment]
Martin - Each field in the controlled vocabulary has a unique ID. If the ID if each item in the DD list must match the FDA, then I need the list. 
In terms of loading the XML, yes I will check if the XML file has the same values as the controlled list, including the IDs.

**Comment by MartinBernard** [comment]
Message forwarded to Peter B (pbx@soundfound.com). We will close this as it addressed his comment
