### ISSUE TITLE
Character Limit (1500)

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#34]
When trying to populate paragraphs throughout the template i received pop up messages indicating that there was a maximum number of characters that was reached (1500 characters).

Did not seem to cause a problem yesterday.

**Comment by maadarani** [comment]
This is part of the validation that Eric sent a while ago. Put a 1500 character limit on each field.

**Comment by MartinBernard** [comment]
That's not true. We should remove it but we can do that at a later date.

**Comment by maadarani** [comment]
it is in the spreadsheet he sent me. If we are adding it later, why remove it?

**Comment by MartinBernard** [comment]
We need to allow for more than 1500 chars. However, please do not change anything for the time being unless instructed otherwise.

Keep this issue open for the time being.

**Comment by MartinBernard** [comment]
REf #62 . close
