### ISSUE TITLE
Load XML

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#35]
I cannot load an xml file, I get an error message.

![image](https://cloud.githubusercontent.com/assets/9659886/10950762/77e5a61c-8307-11e5-8d71-bb8bde1eeced.png)

**Comment by maadarani** [comment]
was is it a file created by the application?

**Comment by MartinBernard** [comment]
Yes

**Comment by MartinBernard** [comment]
Seems to work now. We will close
