### ISSUE TITLE
Web Standards

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#39]
I received a heads-up from our web standards group within IMSD that there are lots of issues with the form where it is not complaint or using incorrect functionality, etc.  The group responsible will be submitting their report to us by Friday. 

I was under the impression that you assured us that everything would be in line with the standards and that only minor changes MAY be required but by the way they were talking its far more than that.

Stand by.

**Comment by maadarani** [comment]
I suspect it is related to the RTE. Usually one thing leads to tens if not hundreds of errors. I will wait for the report to assess.

**Comment by MartinBernard** [comment]
Report attached. There are lots of issues listed. Some of which you gave assurance on at the start of the development of the form so not sure why they are found in the report

<deleted report>

Can you please take a quick look in advance and we should probably meet to discuss.

**Comment by maadarani** [comment]
The report actually is not bad at all; it is long, but it shows pass, n/a, or fail. Some of the items listed were tested before we finished the product and the issues do not exist. Some are related to the fact we are using RTE and not text field, some are either related to the WET footer/header, which we have not finished, and the rest are minor. I am actually pretty happy with this report.

Maybe we can meet next week to review? I am away on Monday/Tuesday, so maybe we can re-schedule for Thursday?

**Comment by MartinBernard** [comment]
OKay good to hear that. I got worried after seeing 15 pages of issue -- that's re-assuring. 

Let's use our Friday meeting 11am to review. In the mean time, I'd like you to spend one hour max on going through the document and appending your comments and response that way our meeting will be more productive.

**Comment by MartinBernard** [comment]
Here's the new report for our review on Friday.

[RDIMS_EAST-#335466-v1-Web_Standards_and_Web_Renewal_Compliance_Report_-_....docx](https://github.com/hres/pmp/files/43179/RDIMS_EAST-.335466-v1-Web_Standards_and_Web_Renewal_Compliance_Report_-_.docx)

**Comment by MartinBernard** [comment]
@maadarani - please provide estimate only for the correction required based on the report provided by our web standards group

**Comment by MartinBernard** [comment]
Estimated 3 days worth of effort for Mike to complete

**Comment by MartinBernard** [comment]
@dbeauvai - this will go to the new resource coming in.

**Comment by MartinBernard** [comment]
@dbeauvai / @OttawaOn - I hope the knowledge transfer went well. Please note report from our web standards group. We will need to address momentarily.

**Comment by OttawaOn** [comment]
Thanks so much!
I got your message!
Ching

**Comment by MartinBernard** [comment]
Close for now. We'll include this task in item #62
