### ISSUE TITLE
Footnote

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#4]
Cover - Footnote

Sponsors need a section for footnotes         

Priority - M

**Comment by maadarani** [comment]
Where do we put the footnote, just below "Sponsor address"?
Why kind of textbox, normal or richtextbox?

**Comment by MartinBernard** [comment]
Footnote field should be a rich text and inserted below the Submission Control No: field.

Also noted that the "add/or" is still an issue on the cover page. please correct to "and/or".
