### ISSUE TITLE
Declarations

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#42]
Peter B to provide Mike
(1) XML Prolog
(2) Document Declaration
(3) Document Definition
(4) Codes

**Comment by MartinBernard** [comment]
@peterbomberg --- Mike will use his remaining 10 days on his contract to do this activity. Where are we with that?

**Comment by peterbomberg** [comment]
Working on the schema, but honestly it will take way more time than I
planned, how urgent is it for Mike?

**Comment by MartinBernard** [comment]
Mike has 10 days left till end of December so you have time but you'll need to do it within the next two weeks. Hopefully that's feasible

**Comment by MartinBernard** [comment]
Anything else required here or are we waiting for direction after our meeting on the 11th of Jan

**Comment by peterbomberg** [comment]
We are waiting, I am working on it in the background but no direction to
Mike until the 11th.
