### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#44]
@maadarani - Is there a size limit for uploading images? There are some restrictions apparently on image sizes as part of eCTD. We just need to make sure it aligns.

**Comment by MartinBernard** [comment]
@maadarani - we will need to provide an answer to Vik before he goes to CAPRA .

**Comment by maadarani** [comment]
Right now we do not have any restriction. If we need to cap the image size, then we can; I just need to know the size.

**Comment by MartinBernard** [comment]
2gb per image file - technical limitation.

**Comment by MartinBernard** [comment]
Peter to find technical details and get back to us.
@maadarani  - no action required for you now.

**Comment by MartinBernard** [comment]
Email from Peter ----- They cap images at 1MB, however this is for images included in a XML document. I would recommend we allow significantly larger images (as this is based on scanning a page not on computer generated images).

Response from Vik -----     Not sure I completely follow.  Why would we do something differently?   The XML file is generate on the user's workstation or programmatically  from their software tools. 
While the images in the Structured PM themselves might be scanned, given the context in which  they are being ‎used, the FDA limit seems reasonable. Something worth testing in the pilot perhaps

**Comment by MartinBernard** [comment]
Email from Peter -----The images must be referenced from the SPL document (otherwise they will be deleted in many XML CMS systems as they are orphans). The file size limit of 1MB in my mind should be raised as a single hi resolution photo can easily be 2-10MB.

**Comment by MartinBernard** [comment]
There no technical reason why we can't allow them to submit hi res photo.  
Let's set it from 2-10mb.
We will confirm and validate statement during pilot phase.
