### ISSUE TITLE
Controlled Vocabulary Drupal Module

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#50]
Peter, I've asked our sysadmin to create a DRUPAL site so we can start building the CV management tool.

As per your discussion with Vik, we need the following:

1) Technical specs (i.e.: column def, configuration, etc.)
- Create Code Tables for CVs and their respective field requirements.
  2) Interface specs / requirements
  3) management and governance authority 
  4) lifecycle management component

**Comment by MartinBernard** [comment]
My students is all briefed up on this issue / ask. 

If you provide me the specs etc soon then we can have something in place by end of week.

With respect to the ID and date stamp, (1) there are table ID which is class_code and (2) there is no change time stamp for any of the code tables in DPD

**Comment by MartinBernard** [comment]
First iteration of data capturing repository has been created. IMS account created for Peter B.

**Comment by MartinBernard** [comment]
First draft version is ready to be viewed.

drupal.hres.ca/vocabulary

username : reader
pw : reader

**Comment by MartinBernard** [comment]
Many modifications and changes made a result of email exchange between peter and I. French values will be loaded by eod tomorrow..

**Comment by MartinBernard** [comment]
Message from Peter - 

Can we capture notes for the implementation and maintenance guide?

The description field will contain a reference to the new code for any that are superseded and all non-approved must have an explanation of the reason for the non-approved status.

**Comment by MartinBernard** [comment]
All CVs has been entered including all Section ID, Template ID, Document ID as defined in Peter's guidance doc.

I will need to sit with Eric and go through the list to validate values entered.

**Comment by peterbomberg** [comment]
I apologize but I have missed some items, please add the following items:

To the Section ID table:
220-70  Adverse Drug Reaction Narrative
230-70  Serious Drug Interactions
230-80  Drug Interactions Overview
390-30  Missed Dose

**Comment by MartinBernard** [comment]
390-30 Missed Dose was missed. I've now entered it.
