### ISSUE TITLE
Work Status Update???

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#51]
Status Update on #39 , #40 , #45 , #48  

Most important is the upload of your code to GIT.

**Comment by MartinBernard** [comment]
@maadarani - sorry to pester you with all these updates but last week you mentioned that all of the above would be completed in relative short order. I would like an update please as soon as possible.

**Comment by maadarani** [comment]
@MartinBernard Sorry Martin. I should have the ToDo issues completed this weekend (except the web report, since you asked to hold on for this one)

**Comment by MartinBernard** [comment]
thx Mike.
