### ISSUE TITLE
CV clarification

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#56]
Martin can you verify if A or B is correct

A)
240-50  Reconstitution
240-60  Oral Solutions
240-70  Parenteral Products

B)
240-50  Reconstitution
240-50-10   Oral Solutions
240-50-20   Parenteral Products

**Comment by MartinBernard** [comment]
Right now it is tracked in Drupal as (A)

**Comment by peterbomberg** [comment]
Can you please table with PM WG as your walkthrough implies B, so I would like to clarify
