### ISSUE TITLE
PM Working Group - Issues Needing Resolution

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#61]
1) Who is identified in the author field?
FDA options are Labeler, Registrant, Establishment, Agent and Importer, what does HC require in this field?

Recommendation that we force the author = labeler?

pbx: Update, I think it should be the Registrant, but not 100% certain.

2) Need to clarify what does this mean, can we use the FDA Effective Date or ?

pbx: update, the issue is on our application we have a Date of Preparation: but the SPL has an Effective Time.

3) We need to validate the assumption that Pristine PM's can only use CV terms where the status is approved? or can they also use pending?

pbx: update, this is not relevant if we move to using a maint org for our CV's as they only have approved and obsolete.

4) Need 2-3 complete samples of the pristine PM

5) Need the rules for the title for a Pristine PM

pbx: I will have to get back to this one.

6) Need to verify if A or B is correct for the CV for Dosage and Administration

A)
240-50 Reconstitution
240-60 Oral Solutions
240-70 Parenteral Products

B)
240-50 Reconstitution
240-50-10 Oral Solutions
240-50-20 Parenteral Products

pbx: I will update the guidance and the CV's (as well as send you a correction email for the CV in Drupal).

7) Explain the rendering approach and the impact. Escalate until we have resolution and forecast the impact to the project.

8)  Can we formally adopt the FDA Marketing Category and Product Type CV (OID: 2.16.840.1.113883.3.26.1.1) or do we need a HC CV list.

This has a significant effort aspects as it changes the rendering engine and rules.

9) Do we need a HC CV for equivalency or can we formally adopt the FDA's CV

OID 2.16.840.1.113883.3.26.1.1

10) We need a decision on the Section Numbering:

```
 1. should the sections have a number?

 2. If numbered should it be continuous or do we allow gaps (for optional sections). Fixed is impossible with a non fixed structure.
```

11) do we need to be able to add subsections in the Clinical Trials Section?

pbx: I will update the CV and guidance

12) App calls the subsection Clinical Trials Overview validation calls it Clinical Trials which is it?
1. The closer we are to the FDA SPL model the easier it is from both a technical and a sponsor perspective, this makes extending the FDA model very advantageous but we need to be clear that when they have registered a term we can use it as is, not redefine it.  

HC can add terms that the FDA does not use.

**Comment by MartinBernard** [comment]
> 1) Who is identified in the author field?
> if we are to keep in line with the FDA then we would should select whatever is closer to "DIN Owner" or  "Sponsor"
> 
> 2) Need to clarify what does this mean, can we use the FDA Effective Data or ?
> Not sure what this means. I will need more explanation. Sorry
> 
> 3) We need to validate the assumption that Pristine PM's can only use CV terms where the status is approved? or can they also use pending?
> The former would be correct but we will confirm with the WG to make sure 100%
> 
> 4) Need 2-3 complete samples of the pristine PM
> Abilify  [PM00030921.PDF](https://github.com/hres/pmp/files/57552/PM00030921.PDF)
> Advair  [PM00031664.PDF](https://github.com/hres/pmp/files/57554/PM00031664.PDF)
> Lipitor  [PM00030467.PDF](https://github.com/hres/pmp/files/57555/PM00030467.PDF)
> 
> 5) Need the rules for the title for a Pristine PM
> Propose something and we can discuss.
> 
> 6) Need to verify if A or B is correct for the CV for Dosage and Administration
> B is correct as per 2004 PM Template
> 
> 7) / 8) / 9) / 10)
> Let's discuss on Friday. Not sure I quite grasp everything here.
> 
> 11) do we need to be able to add subsections in the Clinical Trials Section?
> Yes
> 
> 12) App calls the subsection Clinical Trials Overview validation calls it Clinical Trials which is it?
> This is a known section that needs to be corrected based on resolving #25

**Comment by MartinBernard** [comment]
@peterbomberg - as discussed today, please add your additional comments and issues here for discussion and decision tomorrow when we meet with @vksrivas

**Comment by MartinBernard** [comment]
@peterbomberg - Is there anything else we need to discuss before or are we all squared up with issues above? Do you need anything from me?

**Comment by peterbomberg** [comment]
We are all good until the 11th

**Comment by MartinBernard** [comment]
@peterbomberg 

13) Input on the following Q&A is required:

Q:  What is the naming convention for the XML files?

A:  The naming convention will automatically be assigned by the tool being provided. However, if companies have their own publishing tool, the following naming convention is recommended. 
PRODUCT-NAME_CONTROL-NUMBER_DATE-SUBMITTED.XML
Where:
PRODUCT-NAME: brand name as per the PM
CONTROL-NUMBER: DSTS assigned control number for the case submission
DATE-SUBMITTED: The date the license holder submitted the XML file. This date should match the date on the cover page.

**Comment by peterbomberg** [comment]
The FDA uses the following file naming convention:

The SPL file name is the document id followed by “.xml”, where the document
id is the root attribute of the id element in the Document Information
Section.

**Comment by MartinBernard** [comment]
FAQ updated accordingly.

**Comment by MartinBernard** [comment]
@peterbomberg - can we discuss today. I'd like to know if I need to ask/clarify anything the WG members during our meeting tomorrow?

**Comment by peterbomberg** [comment]
We should clarify/verify so yes lets talk today.

**Comment by MartinBernard** [comment]
1) agree. sponsor. done. however, it doesn't map to the FDA model.
2) equivalent to FDA Effective Date. Date of Revision takes precedence. Rules to be further defined.
3) Pending discussion with OSIP and MC for decision.
4) done.
5) done.
6) done.
7) Hold until further direction.
8) on hold
9) on hold.
10) Not numbered. It'll be sequential.
11) done.
12) Select as " Clinical Trials "
13) done.
