### ISSUE TITLE
Mike Maadarini ToDo List

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#63]
For now
1) Confirm amount of days left
2) Update code to GIT
3) Remove "Add" button for all paras

**Comment by MartinBernard** [comment]
> 3) Remove "Add" button for all paras
> Under Part I , it's applicable to Contraindication, Serious Warnings & Precautions
> Under Part III, it's applicable to Serious Warnings and Precautions,

**Comment by MartinBernard** [comment]
@maadarani - update please.

@vksrivas - FYI

**Comment by maadarani** [comment]
1. 9 days left
2. will do today
3. will finish it today

**Comment by MartinBernard** [comment]
> will do today
> will finish it today

still pending.

**Comment by maadarani** [comment]
#3 finished yesterday.
#2 having issues uploading. Will update you.

**Comment by MartinBernard** [comment]
I noticed all above mentioned item have been completed - thx. I will close this issue and open another one with your next set of tasks which will take care of the remaining days.
