### ISSUE TITLE
Create Presentation re CV's

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#64]
Peter to create a presentation to start the discussion re: CV approach.

**Comment by MartinBernard** [comment]
Very good first draft. Include my comments and share with Vik for his initial reaction. Meeting scheduled Jan 11th followed by OSIPMC Jan 17th (i think)

**Comment by peterbomberg** [comment]
Do you have any examples where we use the same term to mean 2 different
things?

**Comment by MartinBernard** [comment]
I checked with SME within OSIP and we can't think of any examples. Our HC list was derived from the FDA so I doubt it'll be the case.

**Comment by peterbomberg** [comment]
Ok, this is good news. I will update the deck

**Comment by MartinBernard** [comment]
I would suggest leaving it in even if it means asking the question when we meet with them on the 11th of Jan.

**Comment by peterbomberg** [comment]
done

**Comment by MartinBernard** [comment]
Thx. 

@vksrivas - when you eyes balls are okay, pls take a look.
