### ISSUE TITLE
CV in Drupal

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#65]
Please add Clinical Trials - Misc. with an ID of 310-40 to the section ID table

Also please correct the ID's for Oral Solutions  it should be 240-50-10 not 240-60 and Parenteral Products  should be 240-50-20 not 240-70 in the section ID table.

I am not sure if it's spelled right?

Peter

**Comment by MartinBernard** [comment]
Email sent to @ericgrandmaison for action. It'll be done tomorrow.

**Comment by ericgrandmaison** [comment]
Done.
