### ISSUE TITLE
Steps for deployment

### ISSUE THREAD

**Issue by dbeauvai** [hres/pmp#69]
@maadarani  as discussed can you provide screen shots of the steps to deploy the application on iis-rep.hres.ca and identify the steps

**Comment by MartinBernard** [comment]
@maadarani - approved work, pls proceed.

**Comment by MartinBernard** [comment]
@maadarani / @dbeauvai - status update pls?

**Comment by OttawaOn** [comment]
I will wait for Diane's agreement to update into the GitHub, she told me
to keep at my VM first next week We will discuss put into GitHub.
Ching

**Comment by MartinBernard** [comment]
@maadarani - could you please give us a estimated time to completion so we can plan accordingly?

**Comment by maadarani** [comment]
@MartinBernard @dbeauvai I don't have access to the server anymore. I will wait to gain access again to send you the screenshots.

**Comment by dbeauvai** [comment]
@maadarani - can you put the images here and the steps ? or send to me via e-mail?

Thanks,

**Comment by maadarani** [comment]
@dbeauvai I will when I gain access back to the server.

**Comment by MartinBernard** [comment]
@dbeauvai - progress on this?

**Comment by dbeauvai** [comment]
@MartinBernard - Mike does not have access to the server anymore.  He needs it in order to do the screenshots.

**Comment by MartinBernard** [comment]
@ayoung8 - can you pls action.

**Comment by maadarani** [comment]
To Deploy, simply zip the solution and unzip in this folder. C:\Website\iis.rep.hres.ca. See Screenshots

![2016-01-27 10-50-59 pm](https://cloud.githubusercontent.com/assets/6798647/12634578/d249607a-c548-11e5-8daa-5c9cfaa7476f.jpg)
![2016-01-27 10-51-48 pm](https://cloud.githubusercontent.com/assets/6798647/12634581/d568f266-c548-11e5-8072-be1d25345c62.jpg)

**Comment by ayoung8** [comment]
This site is now synced with GitHub on the server. All you have to do is connected to the server and within github for windows sync any changes. (Eric knows how to use github for windows in case anyone needs a refresher ... it will take about 30 seconds)
-------------- NOTE: --------------------------
All changes MUST be made to this repository, if you are using Visual Studio then have it sync with this repository for any changes, if you skip this step do not expect your changes to go live. period. 
------------ END NOTE ----------------------

**Comment by dbeauvai** [comment]
I have added the instructions in our Technical Guide Document.  We will test the synced and deployment asap.

**Comment by MartinBernard** [comment]
@dbeauvai - it's the same guide entered in #74 ? If so, can you please attach the update version in that git issue?

**Comment by OttawaOn** [comment]
Hi! Mike,
I zip the project Could I email to you

**Comment by MartinBernard** [comment]
@dbeauvai - pls note that we have expired Mike's time and I'm not sure what sure that @OttawaOn meant by her last comment.

**Comment by dbeauvai** [comment]
@MartinBernard - I will follow up with her.

**Comment by OttawaOn** [comment]
Diane, Hi, Please receive my status report.
