### ISSUE TITLE
PM Technical Code Guide

### ISSUE THREAD

**Issue by dbeauvai** [hres/pmp#72]
@maadarani @OttawaOn @MartinBernard 

Please find attached a draft of the modified Technical Guide.

I have included a project description (Martin feel free to update it if you want), an architecture diagram, a code repository section and a deployment section (I will complete it once I get info from Mike).

Thanks,
[PM Technical Guide Document.docx](https://github.com/hres/pmp/files/97932/PM.Technical.Guide.Document.docx)

**Comment by MartinBernard** [comment]
Very good. Thx. Let's use this ticket to track progress of the guide.

**Comment by MartinBernard** [comment]
@vksrivas - take note. I know you like this type of stuff.

**Comment by OttawaOn** [comment]
Yes, Mike,
Thanks for your email!
I have read the Technical Guide, it is very useful.
I edit the Cover page and Part one.
Ching

**Comment by MartinBernard** [comment]
@dbeauvai - pls attach the revised version as mentioned today in the ticket

**Comment by OttawaOn** [comment]
Wait till on Monday Feb 1, 2016
I will merge the code with Diane and Min. then upload the project.
Ching

**Comment by dbeauvai** [comment]
@MartinBernard - please find attached the revised version of the PM Technical Guide Document.
[PM Technical Guide Document.docx](https://github.com/hres/pmp/files/113957/PM.Technical.Guide.Document.docx)
