### ISSUE TITLE
PM Guidance Document - update

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#75]
@peterbomberg - can you come up with a 2-3 liner blurb that will be going in the PM Guidance Document indicating that we'll be doing work on the technical side of things so for more information go <to our guidelines> etc.

**Comment by peterbomberg** [comment]
Which PM Guidance Document, the one for the SPL document or the application? (We may have  too many documents called PM Guidance).

I have 2 guidance documents (Guidance for HC SPL Documents and Guidance Document PM) these are for SPL documents, so I am guessing the PM Guidance is for the application.

Here is my proposed blurb:

Additional information on the technical aspects (including the schema, samples, use cases and validation) of the overall SPL document can be found in the “Guidance Document – General SPL Documents” document, while the technical aspects specifically relating to the Pristine Product Monograph SPL document can be found in the “Guidance Document - SPL Pristine PM”

**Comment by MartinBernard** [comment]
Seriously. I should have been more prescriptive in my request and yes I agree we have too many guidance named the same thing. I was referring to the operation/business PM guidance found here: http://www.hc-sc.gc.ca/dhp-mps/prodpharma/applic-demande/guide-ld/monograph/index-eng.php

They are revising it now so they want to make sure there's a statement in there to reflect what we're doing on our initiative. Let's keep it straight-forward without naming or mentioning the name of our guidances....

BTW - good work on the last version of the consolidated version of the deck

**Comment by peterbomberg** [comment]
Ahh, well in that case my blurb might actually be perfect and I am glad to hear they are updating the business Guidance Document however this means that we need a decision ASAP. Is the Pristine PM in XML format a nice to have or a must have.

**Comment by MartinBernard** [comment]
Yes we're at that cross road where we need to make a decision asap. Let's put that final "processing" decision in the eCTD guidance / instructions document but for the sake of this GD, lets' keep it somewhat vague but ensure we address the fact that there's a statement in there that will inform users where to go for op /technical reference.  This request comes from Michell Remillar (TPD rep)

**Comment by peterbomberg** [comment]
Revised blurb:
This document provides guidance on the content and context from a business perspective. There are additional guidance documents that describe the technical aspects.
The requirement is to submit a Pristine PM in SPL format as part of the submission, this can be done in one of 2 ways both are valid and result in valid content being created. 
• Health Canada has provided an open and free application that can be used to create a SPL file, this file is saved locally and included with the submission, the technical guidance documents for this approach is detailed in ???. 

o   It is also possible to use the application with an XML file generated externally as a validation mechanism, while this approach may seem a bit odd, it enables sponsors to create content offline and load it for validation. This approach is covered in the application technical guidance.

• Alternatively a native SPL capable XML editor can be used to create the SPL file that is included with the submission, the technical aspects (including the schema, samples, use cases and validation) of the overall SPL document can be found in the “Guidance Document – General SPL Documents” document, while the technical aspects specifically relating to the Pristine Product Monograph SPL document can be found in the “Guidance Document - SPL Pristine PM”

**Comment by MartinBernard** [comment]
Thx again Peter. Great.

We'll have to most likely change the naming of your guidance but that's something we can deal with later on.
