### ISSUE TITLE
First Page Changes

### ISSUE THREAD

**Issue by MartinBernard** [hres/pmp#76]
(1) Ability to input multiple active ingredients and corresponding strengths for one tablets. For example, see PM ATRIPLA. We need to be able to capture these. In other words, we need an ADD/REMOVE button wrapped around the first table to be able to capture multiple ingredents.

[PM00030932.pdf](https://github.com/hres/pmp/files/111267/PM00030932.pdf)

(2) We also need to ability to capture joint venture agreements where two companies own the product etc. so possibly and ADD/REMOVE button for sponsor name and sponsor address.

**Comment by MartinBernard** [comment]
@peterbomberg & @kpaschakis ---- please help @dbeauvai understand this requirement or contact me if above 1) and 2) are unclear.

**Comment by peterbomberg** [comment]
Lets talk about the joint venture approach, that is not in line with the FDA. if a separate legal entity then  single, if a true joint venture then one is lead. I have to see if you can have 2 equals.

**Comment by peterbomberg** [comment]
Peter to create a business guidance update list/document and note how to address 2 above. 1) needs to be corrected.
