### ISSUE TITLE
Recommendation for splitting the approach (SPL and SPL Lite)

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#77]
Rather than making the online application being able to handle all appropriate SLP aspects, it may be advisable to change the position and at this time say that the application will not be capable of handling a full SPL file but rather save an interim format, over time it will be aligned with SPL.

This means that a sponsor will NOT be able to load a full SPL file into the application for validation however they can still include them in a submission.

It also means that the xml file generated by the application will not comply with the overall SPL schema.

This also means we need to look at a unique ID's (such as DocID, etc..) for the SPL Lite file.

**Comment by MartinBernard** [comment]
@peterbomberg - noted, you may want to get full confirmation with @vksrivas  or bring up at Wednesday's meeting with the FDA.

**Comment by peterbomberg** [comment]
I would rather the 3 of us talk about it internally first. I can join via telco tomorrow after 3
Peter

--

**Comment by peterbomberg** [comment]
Another benefit of this split is we could phase in the SPL file support thus buying time for the CV cleanup. As only 4-5 CV's are needed for the application (and we can even reduce it to 2-3 if needed. However for the full SPL we need at least 15 possibly as many as 30 CV's for the sections we require. (I have started identifying them as per Martin's and my conversation today and am 1/3 of the way trough the product section where the majority are used and permitted).

**Comment by MartinBernard** [comment]
Good point. Let's make sure this is discussed with @vksrivas  before I leave.

**Comment by MartinBernard** [comment]
@peterbomberg - tbd and email to be drfted for Vik's perusal. This week pls.

**Comment by MartinBernard** [comment]
SPL Lite recommended. Email sent today to Vik for confirmation and approval.
