### ISSUE TITLE
CV related questions.

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#78]
To be resolved in the CV meetings:
1. Do we have a HC code system for Language? If not can we adopt ISO 639-3>
   <languageCode code="eng" codeSystem="1.0.639.3" displayName="English”/> Note 3 char
2. Do we have a HC code system for DIN Owner and other companies identified in the SPL files? If so how/what/etc if not do we use the DUNS number?
3.  Do we have a HC code system for country codes, if not can we adopt ISO 3166-1 
    <country code="USA" codeSystem="1.0.3166.1.2.3">USA</country> Note 3 char
4. Active and non active ingredients, I need the CodeSystem and so on.
5. I need a CV for shape, colour, and all other aspects for the product section.
6. Need to resolve the excerpt question, do we permit everywhere or follow FDA lead? See below:
   Excerpts occur only in sections with the following codes: 34066-1 (Boxed Warning), 43683-2 (Recent Major Changes), 34067-9 (Indications and Usage), 34068-7 (Dosage and Administration), 43678-2 (Dosage Forms and Strengths), 34070-3 (Contraindications), 43685-7 (Warnings and Precautions), 34084-4 (Adverse Reactions), 34073-7 (Drug Interactions), 43684-0 (Use in Specific Populations), 49489-8 (Microbiology) 
   An excerpt in the adverse reactions section (34084-4) includes the statement: "to report suspected adverse reactions" and "1-800-332-1088" (different telephone number for documents of type 53404-0 – “Vaccine Label”). 
   If there are highlights excerpts, then the title for the SPL file includes the text string (without the quotation marks): “These highlights do not include all the information needed to use” “see full prescribing information for” and “Initial U.S. Approval”
7. We will need a CV for Marketing Status and Marketing Category.
8. Need to review all of section 4.10.3.3 and 4.10.3.4 of the General SPL Guidance to address the codes used in the product data section
9. We need an Equivalency CV

**Comment by MartinBernard** [comment]
@peterbomberg - will be resolved after we send your list of CVs to OSIP and we have an formalized direction / approach. I would like to get this completed and closed by end of next week.

**Comment by MartinBernard** [comment]
@peterbomberg - can we close this given the email to OSIP and the email we drafted to Vik which I will send momentarilly

**Comment by MartinBernard** [comment]
Tentatively closing. We can reopen if need be
