### ISSUE TITLE
Rendering Realted

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#79]
I believe we agreed that sections are not numbered, this should however be documented so I am adding it to the business guidance info

**Comment by MartinBernard** [comment]
@peterbomberg - no urgency on this but looking to close this ticket if you've already action ed it.

**Comment by peterbomberg** [comment]
Work on this item has not been started, and should wait until the SPL Lite
approach is formalized.

```
          Peter Bomberg
```

email: pbx@soundfound.com

cell: +1 613.769.1142

_From:_ MartinBernard [mailto:notifications@github.com]
_Sent:_ Wednesday, February 24, 2016 8:57 PM
_To:_ hres/pmp
_Cc:_ peterbomberg
_Subject:_ Re: [pmp] Rendering Realted (#79)

@peterbomberg https://github.com/peterbomberg - no urgency on this but
looking to close this ticket if you've already action ed it.

**Comment by MartinBernard** [comment]
I will close but pls track if this work you required to do.
