### ISSUE TITLE
controlled lists

### ISSUE THREAD

**Issue by ericgrandmaison** [hres/pmp#8]
Part I - SUMMARY PRODUCT INFORMATION - 

Use controlled lists:
Route of Administration (controlled list)
Dosage form (controlled list)         

Priority - H

**Comment by maadarani** [comment]
Please confirm.
Only "Route of Administration" and "Dosage form" will be dropdown lists (getting values from controlled list xml)
"Dosage Form(s) and Strength(s) " will NOT be in separate columns just like in Cover page

**Comment by MartinBernard** [comment]
RoA, DF, schedule lists have been provided. PLease go ahead and load in.

**Comment by MartinBernard** [comment]
You can also use the DPD online pick list for dosage /route/ schedule found here: http://webprod5.hc-sc.gc.ca/dpd-bdpp/index-eng.jsp

They should be identical to the lists I sent you.

**Comment by maadarani** [comment]
OK. So the DF is there, but we don't have root of administration and schedule. Where do these map to?

**Comment by MartinBernard** [comment]
They are all there.

**Comment by MartinBernard** [comment]
Units of Measure List (eng / fr)
Please disregard the ID and Inactive date column.

[metric_unit_Oct_2015.xlsx](https://github.com/hres/pmp/files/21718/metric_unit_Oct_2015.xlsx)

**Comment by MartinBernard** [comment]
see item #3 for action and reference. CLose
