### ISSUE TITLE
SPL compliant XML files

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#80]
We need to address the requirement to generate an SPL compliant XML output file.

There are 2 aspects to this, the first being creating rules driven validation that must be executed prior to saving the file (ideally tied to a validate button as well as to the save button). Any validation error needs to be flagged interactively to the user so they can address it.

The second aspect can be done behind the scene and that is to generate the actual output file in accordance to the 2 SPL Implementation Guides (The general SPL guide and the Pristine PM specific one).

**Comment by MartinBernard** [comment]
Noted and recognized work by Diane.. Will be captured as part of Diane;s work spreadsheet.
