### ISSUE TITLE
reversed code and code system

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#86]
on line 43, and possibly other places you have reversed code and code system

<code code="2.16.840.1.113883.3.989.5.1.4.1.8" codeSystem="48780-1" displayName="SPL product data elements section" />

This should be:

<code code="48780-1" codeSystem="2.16.840.1.113883.3.989.5.1.4.1.8" displayName="SPL product data elements section" />

**Comment by spacejang** [comment]
Fixed
