### ISSUE TITLE
Empty Attributes

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#87]
I have discovered you have included empty attributes in the XML you generate, the problem is that the document wont validate that way as "" is often not an allowed value for an element as an example on line 52, 58 etc..

**Comment by spacejang** [comment]
Hello Peter,

Only remove Empty Attributes? or all of empty elements?

**Comment by peterbomberg** [comment]
Remove empty elements

**Comment by spacejang** [comment]
Fixed
