### ISSUE TITLE
Version #

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#89]
When I load a file with a version number you do not set it properly in the application

**Comment by spacejang** [comment]
What do you mean?
Version number loaded as it is. Please give me steps..

**Comment by peterbomberg** [comment]
Do you want me to email you or update Git?



              Peter Bomberg

email: pbx@soundfound.com

cell: +1 613.769.1142



*From:* Jangyoung [mailto:notifications@github.com]
*Sent:* Monday, January 23, 2017 11:08 AM
*To:* hres/PM
*Cc:* peterbomberg; Author
*Subject:* Re: [hres/PM] Version # (#89)



What do you mean?
Version number loaded as it is. Please give me steps..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hres/PM/issues/89#issuecomment-274530502>, or mute the
thread

**Comment by peterbomberg** [comment]
I uploaded a XML file where the version number was set but the form remained blank.

**Comment by peterbomberg** [comment]
I figured this out, you are setting the value as content it should be set as an attribute.

The XML should read <versionNumber value="1"/> not <versionNumber>1</versionNumber>

**Comment by peterbomberg** [comment]
Blah, I can not load XML into the content, so the issue is it should be: (I am removing the delimiters

versionNumber value="1"/ not versionNumber5/versionNumber
