### ISSUE TITLE
only Author saves

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#91]
Product and Part 1-3 are empty when I save as draft

**Comment by peterbomberg** [comment]
Actually this happens as soon as I try to create product info.

If I only create part 1-3 content these sections are included in the XML

**Comment by spacejang** [comment]
Could you please re-try it since I deployed new version in the morning.
Or
Could you please give me steps what you've done.

**Comment by spacejang** [comment]
Fixed
