### ISSUE TITLE
codeSystem="2.16.840.1.113883.3.989.5.1.4.1.10"

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#92]
there is an extra space in displayName="2004 Product Monograph Template  Standard" />

**Comment by spacejang** [comment]
What do you mean?
Please give me more detail. 
Thanks.

**Comment by peterbomberg** [comment]
Details in the message, there is an extra space between the word Template
and Standard

              Peter Bomberg

email: pbx@soundfound.com

cell: +1 613.769.1142



*From:* Jangyoung [mailto:notifications@github.com]
*Sent:* Monday, January 23, 2017 11:11 AM
*To:* hres/PM
*Cc:* peterbomberg; Author
*Subject:* Re: [hres/PM] codeSystem="2.16.840.1.113883.3.989.5.1.4.1.10"
(#92)



What do you mean?
Please give me more detail.
Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hres/PM/issues/92#issuecomment-274531521>, or mute the
thread
