### ISSUE TITLE
missing sub sections

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#93]
If I enter content into a subsection without creating content in the parent section then it is omitted in the XML

Step 1) Create content in Geriatrics (210-210-40)
Step 2) Save Draft
Step 3) Review XML , it is missing section 210, 210-210 and 210-210-40, ie none of the 3 sections are in the XML
Step 4) Create content in Warnings and Precautions (210)
Step 5) Save Draft
Step 6) Review XML and it's all good (ie all 3 sections are there with the right content)

**Comment by spacejang** [comment]
Fixed

**Comment by peterbomberg** [comment]
Still occuring
