### ISSUE TITLE
duplicate sections result in no content

### ISSUE THREAD

**Issue by peterbomberg** [hres/pmp#95]
If I try to create content twice in the same section 210-10 as an example the resulting XML file is missing 210 and 210-10

**Comment by spacejang** [comment]
Fixed

**Comment by spacejang** [comment]
Hello Peter,

Most of dropdown list has its own value and I save it as Key and Value.
So, the way you test does not work since the Key  must be unique.

If you select "210-10" 2 times...I only save the first one....
I will explain it when we have a meeting.
